openapi: 3.0.1

info:
  title: ms-banking-transactions-api
  description: API for ms-banking-transactions
  version: 1.0.0
servers:
  - url: https://localhost:8094
tags:
  - name: ms-banking-transactions-api
    description: API for ms-banking-transactions
paths:
  /transactions:
    get:
      summary: Retrieve all transactions
      operationId: retrieveAllTransactions
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Transactions'
    post:
      summary: Save new transaction
      operationId: saveTransaction
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TransactionDTO'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TransactionDTO"
    put:
      summary: Update an existing transaction
      operationId: updateTransaction
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TransactionDTO'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TransactionDTO"
  /transactions/{id}:
    parameters:
      - name: id
        in: path
        required: true
        description: transaction ID
        schema:
          type: string
    get:
      summary: Retrieve a transaction
      operationId: retrieveTransaction
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TransactionDTO"
    delete:
      summary: Delete a transaction
      operationId: deleteTransaction
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TransactionDTO"
  /transactions/{customerId}/{purchaseId}:
    parameters:
      - name: customerId
        in: path
        required: true
        description: customer ID
        schema:
          type: string
      - name: purchaseId
        in: path
        required: true
        description: customer ID
        schema:
          type: string
    get:
      summary: Retrieve customer's purchase transactions
      operationId: retrieveCustomerPurchaseMovements
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Transactions'

components:
  schemas:
    Transactions:
      type: array
      items:
        $ref: "#/components/schemas/TransactionDTO"
    TransactionDTO:
      type: object
      properties:
        id:
          type: string
        customerId:
          type: string
        purchaseId:
          type: string
        source:
          type: string
        transactionType:
          type: string
        createdAt:
          type: string
        amount:
          type: number
          format: double
        state:
          type: string
      required:
        - id
        - purchaseId
        - transactionType
        - amount